import Link from "next/link";

export const metadata = {
  title: "Terms of Service - AutoCreator AI",
  description: "Read the Terms of Service for using the AutoCreator AI platform.",
};

export default function TermsOfServicePage() {
  const lastUpdated = "June 13, 2026";

  return (
    <div className="container max-w-4xl mx-auto px-4 py-16 md:py-24">
      <div className="mb-12">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
        <p className="text-muted-foreground text-lg">Last Updated: {lastUpdated}</p>
      </div>

      <div className="max-w-none text-foreground">
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          Welcome to <strong className="text-foreground">AutoCreator AI</strong>. These Terms of Service ("Terms") govern your use of the AutoCreator AI website, platform, and related services (collectively, the "Services"). By accessing or using our Services, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Services.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">1. Account Registration</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          To access certain features of the Platform, you must register for an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. You are responsible for safeguarding your password and for all activities that occur under your account.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">2. Use of Services and AI Tools</h2>
        <p className="text-lg leading-relaxed mb-4 text-muted-foreground">
          AutoCreator AI provides tools to automate content creation (including scripts, videos, thumbnails, and captions) using Artificial Intelligence. You agree to use these tools responsibly. You shall not use the Services to generate, upload, or distribute content that is:
        </p>
        <ul className="list-disc pl-6 mb-8 space-y-3 text-lg text-muted-foreground">
          <li>Illegal, defamatory, or highly offensive.</li>
          <li>Infringing on the intellectual property rights of any third party.</li>
          <li>Designed to deceive or manipulate audiences (e.g., deepfakes intended to cause harm).</li>
          <li>In violation of the Terms of Service of social media platforms (e.g., TikTok, Instagram, YouTube) to which you intend to publish.</li>
        </ul>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">3. Intellectual Property Rights</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          <strong className="text-foreground">Your Content:</strong> You retain all ownership rights to the original text prompts and assets you submit to the Platform. <br/><br/>
          <strong className="text-foreground">Generated Content:</strong> Subject to your compliance with these Terms, AutoCreator AI assigns you all of its right, title, and interest in and to the output generated by the AI based on your prompts. However, please be aware that copyright laws regarding AI-generated content vary by jurisdiction. <br/><br/>
          <strong className="text-foreground">Our Platform:</strong> AutoCreator AI retains all rights, title, and interest in the Platform, including its software, UI/UX, and underlying algorithms.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">4. Social Media Integrations</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          If you use our Platform to publish content directly to third-party social media networks, you must comply with their respective Terms of Service. AutoCreator AI is not liable for any account suspensions, bans, or penalties you may incur on third-party platforms as a result of using automated posting features or the generated content.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">5. Disclaimers</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          The Services are provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the reliability, accuracy, or quality of the AI-generated content. AI technology can sometimes produce unpredictable, inaccurate, or inappropriate results. It is your responsibility to review all content before publishing.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">6. Limitation of Liability</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          To the maximum extent permitted by law, AutoCreator AI and its founders, affiliates, or employees shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or digital assets, resulting from your use of or inability to use the Services.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">7. Changes to Terms</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          We reserve the right to modify these Terms at any time. If we make material changes, we will provide notice through our Platform or via email. Your continued use of the Services after such changes constitutes your acceptance of the new Terms.
        </p>

        <h2 className="text-2xl md:text-3xl font-bold mt-12 mb-6">8. Contact Information</h2>
        <p className="text-lg leading-relaxed mb-8 text-muted-foreground">
          If you have any questions or concerns about these Terms, please contact us at: <br/>
          <a href="mailto:legal@autocreator.ai" className="text-primary font-medium hover:underline mt-2 inline-block">legal@autocreator.ai</a>
        </p>
      </div>

      <div className="mt-16 pt-8 border-t flex justify-between items-center text-sm text-muted-foreground">
        <Link href="/privacy-policy" className="hover:text-foreground transition-colors">← Read Privacy Policy</Link>
        <Link href="/" className="hover:text-foreground transition-colors">Back to Home →</Link>
      </div>
    </div>
  );
}
